# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Ideas
    url: /#ideas
    weight: 20
  - name: Work
    url: /publications/
    weight: 30
  - name: Writing
    url: /blog/
    weight: 40
  - name: Club
    url: /nfls-ai-club/
    weight: 50
  - name: About
    url: /about-us/
    weight: 60
