# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About Us
    url: /about-us/
    weight: 11
  - name: Blog
    url: /blog/
    weight: 12
  - name: NFLS AI Club
    url: /nfls-ai-club/
    weight: 13
  - name: Experience
    url: /experience/
    weight: 14
  - name: Get Involved
    url: /get-involved/
    weight: 15
